### ISSUE TITLE
Add ability to allow batch explanation

### ISSUE THREAD

**Issue by sakoush** [SeldonIO/MLServer#1008]
Currently we assume in mlserver `alibi-explain` runtime that the user wants to explain an individual inference prediction (no batch). This is true in the case of anchors. However this is a restriction given that other explainers allow for batch, e.g. `kernel-shap`.

One is idea is to allow the user to specify whether an explainer can handle batch in `model-settings.json`

A related point to `kernel-shap` is that the user is likely to want to explain `predict-proba`, which is sometime not the default predictor in inference models.

A possible example for such `model-settings.json` is as follows:

```
{
    "name": "ks_wine",
    "implementation": "mlserver_alibi_explain.AlibiExplainRuntime",
    "parallel_workers": 0,
    "parameters": {
        "uri": "../artifacts/ks_wine",
        "version": "v0.1.0",
        "extra": {
            "explainer_type": "kernel_shap",
            "infer_uri": "http://localhost:8080/v2/models/wine/infer",
            "infer_output": "predict_proba",
            "explainer_batch": true,
        }
    }
}
```

**Comment by adriangonz** [comment]
For `explainer_batch`, instead of configuring that in the explainer runtime, would be enough to just forward whatever requests we receive? As in, if the client sends a batch of requests to explain, then we could just forward that batch down to the Alibi explainer.

**Comment by adriangonz** [comment]
BTW I was also wondering, to simplify the settings structure, should we just

**Comment by sakoush** [comment]
> For `explainer_batch`, instead of configuring that in the explainer runtime, would be enough to just forward whatever requests we receive? As in, if the client sends a batch of requests to explain, then we could just forward that batch down to the Alibi explainer.

There is an assumption in the runtime currently that the payload contains a batch dimension (if `np`), we then get the first batch and remove the batch dimension as explained [here](https://github.com/SeldonIO/MLServer/blob/27ca2573c740109e28da69690c8341260161b6aa/runtimes/alibi-explain/mlserver_alibi_explain/explainers/black_box_runtime.py#L56-L61).
Removing the batch dimension is required for anchors.

So it feels that we need to be able to tell whether to send the request as is (for shap) and transform it a bit (for anchors).

**Comment by sakoush** [comment]
> // should we call this "predictor" instead?

yeah feel more appropriate but I would leave it to a separate Issue as it would require changes to SCv2 as well.?
