### ISSUE TITLE
Support of caching

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/MLServer#1023]
This is a feature request for support of caching for hashable data types as implemented in academic serving systems [Clipper: A Low-Latency Online Prediction Serving System](https://www.usenix.org/system/files/conference/nsdi17/nsdi17-crankshaw.pdf) section 4.2 and also similar frameworks like [Triton inference server](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/response_cache.md). This could be very useful for non custom runtimes like HuggingFace runtime.

**Comment by adriangonz** [comment]
Fixed by https://github.com/SeldonIO/MLServer/pull/1440
