### ISSUE TITLE
How are inference runtime versions managed?

### ISSUE THREAD

**Issue by rehevkor5** [SeldonIO/MLServer#1047]
Based on https://github.com/SeldonIO/MLServer/blob/master/licenses/license_info.csv it appears that MLServer still uses xgboost 1.4.1 even though 1.7.4 is the latest.

This is surprising, because I can't find any reference to 1.4.1 in the code. For example, https://github.com/SeldonIO/MLServer/blob/master/runtimes/xgboost/setup.py#L36 appears to ask for the latest version.

Is there some kind of external mechanism controlling the version of XGBoost, not documented in the Developer Guide? In short: how to update the version of XGBoost in MLServer?

**Comment by adriangonz** [comment]
Hey @rehevkor5 ,

Good spot! The license info seems to be stale - we must have missed adding that to our CI pipeline.

The version of `xgboost` is not pinned by the `mlserver-xgboost` package. Therefore, when building the relevant images, (or when installing the `mlserver-xgboost` package), `pip` will pick up the last version available. You can see the `setup.py` under each runtimes folder, e.g.

https://github.com/SeldonIO/MLServer/blob/f9e084c26fd802d2c3e5de5933fe7e76fab89a33/runtimes/xgboost/setup.py#L36
