### ISSUE TITLE
Unpin protobuf

### ISSUE THREAD

**Issue by harupy** [SeldonIO/MLServer#1089]
Is it possible to unpin protobuf?

https://github.com/SeldonIO/MLServer/blob/ef17509b162cac9f8916b196ea0c4fd7f09a990b/setup.py#L57

This often results in dependency conflicts.

**Comment by adriangonz** [comment]
Hey @harupy ,

Unfortunately, we need to explicitly pin the version of `protobuf` to ensure we don't use `<=3.20.1`, which contains a critical CVE. 

Once all our subdeps update to TF `>=2.12`, which uses a newer version of `protobuf`, we should be able to remove the pin on `protobuf`.

**Comment by adriangonz** [comment]
Hey @harupy ,

On second thought, we've moved the `protobuf` pinned version to a different place. So now, it won't be enforced on the `mlserver` package, but it will be on the official Docker images.

That is, if you install MLServer from PyPi (i.e. as `pip install mlserver`), then `protobuf` will be whatever you have in your environment. However, if you use our official images, those will always have `protobuf>=3.20.3` in the environment.
