### ISSUE TITLE
Custom metrics are not showing up when the model has adaptive batching activated

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/MLServer#1130]
[Custom metrics](https://mlserver.readthedocs.io/en/latest/user-guide/metrics.html#custom-metrics) seems to be not working in the Seldon core V1 wrapped MLServers when the adaptive batching wrapper is enabled. However, when adaptive batching is disabled, everything works perfectly and new metrics are registered immediately. Seems to be some problem with logging [when the model is decorated with adaptive batching](https://github.com/SeldonIO/MLServer/blob/5b740238abafb793b901a203b309814c621416eb/mlserver/batching/hooks.py#L64) that disables the MLServer metric logging capability.

**Comment by adriangonz** [comment]
Thanks for raising this one @saeid93 , we'll check it out :+1:

**Comment by saeid93** [comment]
@adriangonz an update to this is that I cannot monitor the builtin `batch_request_queue ` metric too. Other builtin parameters like `parallel_request_queue ` are working smoothly.

**Comment by saeid93** [comment]
@adriangonz  I just realized that this was some misconfig from my side. I'm closing it as I no longer observing the same issue after solving that problem on my end. Sorry if it has caused some time debugging for you.

**Comment by adriangonz** [comment]
No worries! Thanks for the update @saeid93 :+1:
