### ISSUE TITLE
400. Model is not ready yet

### ISSUE THREAD

**Issue by MikhailKravets** [SeldonIO/MLServer#1134]
This is very peculiar one. I've already raised this issue in [kserve#2882](https://github.com/kserve/kserve/issues/2882) but I think this may be appropriate here because it happens only with `mlserver`.

I run sklearn model as a KServe `InserenceService` with the KNative's 'scaling to zero' feature enabled. The first request to the service (the one that initializes the Pod) always gets:

```json
400 {"error":"Model sklearn-iris is not ready yet."}
```

Log of the mlserver container

```shell
Environment tarball not found at '/mnt/models/environment.tar.gz'
Environment not found at './envs/environment'
2023-05-07 15:50:18,121 [mlserver.parallel] DEBUG - Starting response processing loop...
2023-05-07 15:50:18,122 [mlserver.rest] INFO - HTTP server running on http://0.0.0.0:8080
INFO:     Started server process [1]
INFO:     Waiting for application startup.
2023-05-07 15:50:18,202 [mlserver.metrics] INFO - Metrics server running on http://0.0.0.0:8082
2023-05-07 15:50:18,202 [mlserver.metrics] INFO - Prometheus scraping endpoint can be accessed on http://0.0.0.0:8082/metrics
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
2023-05-07 15:50:19,895 [mlserver.grpc] INFO - gRPC server running on http://0.0.0.0:9000
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)
INFO:     127.0.0.6:0 - "POST /v2/models/sklearn-iris/infer HTTP/1.1" 400 Bad Request
2023-05-07 15:50:21,855 [mlserver] INFO - Loaded model 'sklearn-iris' succesfully.
2023-05-07 15:50:21,856 [mlserver] INFO - Loaded model 'sklearn-iris' succesfully.
```

May it be the problem when `mlserver` mistakenly returns `True` from `/ready` endpoint when the models aren't actually loaded yet? 🤔

P.S. If this helps, I load model from S3 bucket.

**Comment by adriangonz** [comment]
Hey @MikhailKravets ,

While the model is still getting loaded, the `/ready` endpoint will return `False`. In the latest version of MLServer, the `/infer` endpoint will also return a `400` error while the model is not yet ready (previously it would just let the `/infer` request go on). This would explain the difference in behaviour.

Perhaps the readiness probe should just use the model's `/ready` endpoint? As in, the `/v2/models/sklearn-iris/ready` endpoint? This would ensure that when the request gets forwarded by the autoscaler the model is already up and running.

**Comment by MikhailKravets** [comment]
Hi @adriangonz. Thanks for the response. I'm not sure that KServe / KNative requests MLServer's `/ready` endpoint at all. At least, I didn't find it anywhere in the logs.

**Comment by adriangonz** [comment]
Hey @MikhailKravets ,

That would explain why the deployment gets marked as ready even though the model is not. The fix would probably be to use that endpoint as the readiness probe for the deployment in KServe.

Since the fix is not related to MLServer, it may be best to open an issue in the KServe repo so that it can get tackled there. I'll close this one for now, but please feel free to cross-link this issue with the one on the KServe repo.

**Comment by MikhailKravets** [comment]
Of course @adriangonz. Thanks for your support!
