### ISSUE TITLE
Extend `PandasCodec` to support `"category"` dtype

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/MLServer#1197]
`pandas` has a native representation of categorical variables via its `"category"` dtype. This has multiple benefits, for example much smaller memory footprint and opening up more internal tools for manipulating categorical variables as well as connecting with external libraries treating this dtype as part of an API, see more here: https://pandas.pydata.org/docs/user_guide/categorical.html

Why it's particularly relevant for us is that it might be the native representation for some models, e.g. `xgboost` supports native categorical variables via this API: https://xgboost.readthedocs.io/en/stable/tutorials/categorical.html

**Comment by jklaise** [comment]
Just realized that this is a dupe of #631, perhaps we promote that one instead?

**Comment by adriangonz** [comment]
Good spot @jklaise - let's go with #631
