### ISSUE TITLE
Memory consumption with multiple models and multiple parallel workers

### ISSUE THREAD

**Issue by josemalope** [SeldonIO/MLServer#1232]
At the moment the number of parallel_workers is specified at server level and every model is loaded in every worker.

This approach is great for optimizing CPU load distribution, however for multiple models and multiple workers the memory consumption grows exponentially:

| Models | Workers | Memory |
|------------------------- | ------------------------- | ----------------------------- |
| 1 | 1 | 1x1 = 1U |
| 2 | 2 | 2x2 = 4U |
| 3 | 3 | 3x3 = 9U |
| 4 | 4 | 4x4 = 16U |

Which in practice means that for similar models (in terms of CPU load) it is more convenient to have 4 instances of mlserver (1 model per instance, 4x1x1 = 4U memory needed ) instead of an unique instance with 4 models (1x4x4 = 16U memory needed).

I noticed that there is a deprecated parallel_workers config at model level. Would it be feasible to have both configs, i.e., at server level and at model level? So in the example above, we could specify 1 worker per model, resulting in a memory consumption of 4x1 = 4U

What do you think?

**Comment by adriangonz** [comment]
Hey @josemalope !

Thanks for raising this one.

It would definitely make sense. In fact, we're currently exploring adding back support for heterogenous workers (which would bring back the ability to control on how many workers we deploy each worker). This work is tracked in #975. 

I'll close this issue in favour of #975, but happy to continue the discussion there!
