### ISSUE TITLE
Load model in sequential mode when there is more than 1 parallel worker

### ISSUE THREAD

**Issue by josemalope** [SeldonIO/MLServer#1316]
We are using a model that has a memory peak consumption when it is loaded.

The peak is proportional to the number of parallel workers because they are loaded in parallel. In this case it would be beneficial to load them sequentially, so the peak is only 1x irregardles of the number of pararallel workers.

Would it be possible to add such feature?

**Comment by adriangonz** [comment]
Hey @josemalope ,

Thanks for raising this one.

Right now, workers are homogeneous - i.e. every worker loads a copy of every loaded model. 

There's an open issue to add support for heterogeneous workers, which would open the door to control the number for replicas for each model. For instance, having N workers but just a single copy of each model. This is currently prioritised for `1.4.x`, but it's likely it will get delayed to `1.5.x`. 

https://github.com/SeldonIO/MLServer/issues/975

That looks like the solution you're describing above, so I'll close this issue in favour of #975  - but please do correct me if that's not the case!
