### ISSUE TITLE
Adding IntCodec?

### ISSUE THREAD

**Issue by rlleshi** [SeldonIO/MLServer#1323]
Currently, there seems to be no "IntCodec" supported. So to pass a single integer as an input, I'm using the workaround of encoding it as a string and then using `StringCodec` to decode it inside the MLServer microservice.

Do you plan to add such support? Or is there anything I'm missing here?

**Comment by adriangonz** [comment]
Hey @rlleshi, 

If all you want is a list of integers, you should be able to use the data field directly - right?

**Comment by rlleshi** [comment]
Hello @adriangonz 

I want to pass a single integer actually. For example the input request:

```
    inference_request = {
        'parameters': {
            'content_type': 'str'
        },
        'inputs': [
            {
                'name': 'prompt',
                'data': prompt,
                'shape': (1,),
                'datatype': 'str',
            },
            {
                'name': 'max_tokens',
                'data': [200],
                'shape': (1,),
                'datatype': 'int',
            },
...
        ]
    }
    ```
    Currently, I'm passing it as a list so that I can access it from the `TensorData` class. But this is just another workaround.

**Comment by adriangonz** [comment]
Right - the Open Inference protocol is designed around tensors. Therefore, at the payload level the `data` field will always need to be a list. An `IntCodec` seems quite ad-hoc, so I'd not be too keen to add one. 

For this case, the simplest would be to create a `RequestInput` object directly (i.e. `RequestInput(name='max_tokens', datatype='INT32', data=[200], shape=[1])`).
