### ISSUE TITLE
Release patch version to fix security issues?

### ISSUE THREAD

**Issue by jlopezpena** [SeldonIO/MLServer#1361]
As mentioned [in this conversation](https://github.com/SeldonIO/MLServer/pull/1317), the current release of `mlserver` transitively pins (via `fastapi`) a version of `starlette` that has 3 known vulnerabilities.

The version of `mlserver` currently in HEAD relaxes the dependency on `fastapi` enough for those to be fixed, so it would be helpful if a patch release was made to included those changes.

**Comment by adriangonz** [comment]
Hey @jlopezpena ,

Given there's a thread already going on in #1317, I'll close this one to keep the conversation focused there.
