### ISSUE TITLE
Add lockfile to MLServer

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/MLServer#139]
To better support use cases where `mlserver` is used as a library, we shouldn't restrict the dependencies versions too much. Instead, we should look into adding some sort of lockfile (e.g. through Poetry or Conda) that locks the versions in the Docker image (so that the "app-level" environment is kept consistent).

**Comment by PaulEdwardBrennan** [comment]
Hi Adrian. Can you please give some more detailed explanation on what's involved here. 
Thank you.

**Comment by adriangonz** [comment]
Hey @PaulEdwardBrennan , 

This would involve adding a lock file which specifies the exact deps and subdeps that are shipped within each MLServer image. This ensures reproducibility, as well as avoiding scenarios where a subdep of a subdep introduces a breaking change. To achieve this, we'll most likely leverage [Poetry](https://python-poetry.org/). 

Do you have any particular questions around this one?

**Comment by RafalSkolasinski** [comment]
I am gonna look into this one in following days

**Comment by adriangonz** [comment]
Good point! Let me pull that into `v1.1.x`.
