### ISSUE TITLE
OpenNMT CTranslate2 Support?

### ISSUE THREAD

**Issue by cccs-km** [SeldonIO/MLServer#1432]
Hi All!

Really interested in MLServer, it looks like a really neat way to consistently serve ML models of varying frameworks.

I've gone through the documentation and I have 2 questions:
1. Any plans to support OpenNMT CTranslate2 inference engine? It's fairly popular for transformer models.
2. In all the documentation I see a standard set of API endpoints. Is there a way to add a custom endpoint?

Cheers!

**Comment by adriangonz** [comment]
Hey @cccs-km ,

Thanks for your interest in MLServer!

To answer your questions,

1. No plans at the moment - we are always open to external contributions though!
2. Not at the moment, we follow closely the spec outlined by the [Open Inference Protocol](github.com/kserve/open-inference-protocol) and we see that the best value comes from standardising on that set of endpoints.

**Comment by NixTheMan** [comment]
@andwilson mlops-world 2023
