### ISSUE TITLE
Empty fields (except `name`) in the returned metadata when using mlserver-sklearn in KFServing

### ISSUE THREAD

**Issue by wfangchi** [SeldonIO/MLServer#145]
Hi experts,

I was trying to follow the steps listed in https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/sklearn/v2 to setup an InferenceService supporting V2 protocol. The `infer` interface works fine. However when I tried to retrieve the Model MetaData via requests like:

```
curl -v -H "Host: ${SERVICE_HOSTNAME}" http://${INGRESS_HOST}:${INGRESS_PORT}/v2/models/sklearn-irisv2
```

All I got is
```
{"name":"sklearn-irisv2","versions":[],"platform":"","inputs":[],"outputs":[]}
```

Is this expected or am I miss anything? I want to get the intput/ouput tensor metadata. 

Let me know if I should post it in KFServing repo instead. Thanks for the help!

**Comment by adriangonz** [comment]
Hey @wfangchi, 

At the moment, KFServing doesn't forward any of the metadata info down to MLServer. Instead, it expects the user to fill a `model-settings.yaml` file in the same folder as the model weights, which contains this information. 

I'll close this issue in the meantime, but we can continue the discussion on how to improve the flow between KFServing and MLServer on the issue you've opened in the KFS repo: https://github.com/kubeflow/kfserving/issues/1488
