### ISSUE TITLE
Instrument MLServer (tracing, metrics & logging)

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/MLServer#181]
Add support in MLServer to report metrics, logging and tracing through OpenTelemetry.

**Comment by martapodarta** [comment]
Hi Alejandro, just to let you know I started working on this ticket.

**Comment by adriangonz** [comment]
Hey @martapodarta ,

As before, thanks a lot for taking the time to jump into this one! :rocket: 

Just as a heads up, metrics (https://github.com/SeldonIO/MLServer/issues/38) and logging (https://github.com/SeldonIO/MLServer/pull/323) should already be there. So, tracing would be the only remaining one.

From an early initial exploration, OpenTelemetry looked promising (at least for tracing). Although I haven't dived much deeper than that. It would be great to hear your thoughts for this one!

**Comment by adriangonz** [comment]
Done in #1281
