### ISSUE TITLE
mlserver-catboost not on pypi

### ISSUE THREAD

**Issue by tokoko** [SeldonIO/MLServer#1838]
I couldn't find `mlserver-catboost` library on [pypi](https://pypi.org/search/?q=mlserver-&o=). [docs](https://mlserver.readthedocs.io/en/stable/runtimes/catboost.html) seem to indicate it should be there.

**Comment by sakoush** [comment]
fix PR: https://github.com/SeldonIO/MLServer/pull/1839onIO/MLServer/pull/1839

**Comment by sakoush** [comment]
@tokoko thanks for raising this issue, we did the relevant changes and in the next release of mlserver `mlserver-catboost` should be available in pypi.

For now you can build from source in your environment.
