### ISSUE TITLE
Adaptive Batching is enabled but not supported for inference streaming.

### ISSUE THREAD

**Issue by rachidrebik** [SeldonIO/MLServer#1911]
Hi,

I am receiving the following warning on my custom model:

"**WARNING: Adaptive Batching is enabled for model 'models' but not supported for inference streaming. Falling back to non-batched inference streaming**."

What is the problem?

**Comment by rachidrebik** [comment]
@sakoush ,
Thank you for your response. I am not using the streaming functionality in my implementation. My model utilizes the **predict** function instead of **predict_stream**. Since I'm relying on the standard predict method, I believe adaptive batching should still work in my case without requiring changes related to streaming. Could you confirm if this approach is compatible with adaptive batching?
I’m encountering an issue after enabling adaptive batching on MLServer:
I send two parallel requests to the MLServer endpoint based on a custom model with the following format:
{ "inputs": [
{ "name": "images",
"shape": [1,1],
"datatype": "BYTES",
"data": [{
"images": [ ["image.png","image_base64_value"],[.........] ]
} ]
}
]
}
I receive a response for the first request, but the second request returns an empty response in data field.
What is the problem please?can you help me?

**Comment by sakoush** [comment]
@rachidrebik if you provide a set of instructions to reproduce the issue you are raising we can take a look further.

**Comment by rachidrebik** [comment]
@sakoush,
I have a custom inference model to predict text from images. The test without adaptive batching works fine. My custom inference model contains two functions: **load** and **predict**. When I run my Docker container, I get the warning 'Adaptive batching not supported for inference streaming' in the logs.
```
async def load(self):
        logger.info("initializing...")
        'instructions code to load model'
        ....
async def predict(self, payload: InferenceRequest) -> InferenceResponse:
       'instructions code to predire text'
       ...
      outputs.append(
                ResponseOutput(
                    name=request_input.name,
                    datatype=request_input.datatype,
                    shape=request_input.shape,
                    parameters=request_input.parameters,
                    data=res["output"]
                )
            )
      return InferenceResponse(model_name=self.name, outputs=outputs)
```

**Comment by sakoush** [comment]
@rachidrebik 

Thanks, yes we can replicate the issue and we will look into it in the next few weeks.

**Comment by sakoush** [comment]
Until we look into it, maybe try older versions of mlserver as it might be a bug that was introduced recently.

**Comment by rachidrebik** [comment]
@sakoush Any updates on the code test?

**Comment by sakoush** [comment]
@rachidrebik having looked more into this issue now, We think that it is likely that your model is not batch enabled.

Consider a model that takes `[b, n]` elements as input with the first dimension as batch `b`, for adaptive batching to work in mlserver the model needs to be able to output `[b, 1]` (assuming one output per b_i). If the model produces less than b outputs elements then for the remaining requests you will get empty responses, which seems to be the case that you described.
