### ISSUE TITLE
Strict Version Dependency of Pydantic

### ISSUE THREAD

**Issue by lemonhead94** [SeldonIO/MLServer#1920]
Hi there,

I was trying to build a custom Runtime for serving `MLflow Langchain Models` and I noticed that you guys have a strict dependency on pydantic version `2.7.1`. Is there any practical reason not to relax it a bit more, for example `pydantic = ">=2.7.1"` and `pydantic-settings = ">=2.2.1"`.

Reference: [pydantic = "2.7.1"](https://github.com/SeldonIO/MLServer/blob/master/pyproject.toml#L65)

**Comment by sakoush** [comment]
Hi @lemonhead94 yes relaxing pydantic bounds is ok, we welcome contributions if you are willing to submit a PR.
