### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by SergeyShk** [SeldonIO/MLServer#1926]
Is there any plan to add support for Python 3.12? It was released over a year ago and many projects are already making use of it

**Comment by SergeyShk** [comment]
Kind of reminder

**Comment by SergeyShk** [comment]
@sakoush Alright, could you share the information on what needs to be done to update the supported version of Python?

**Comment by shivakrishnaah** [comment]
@sakoush I would like to work on this issue. Made few changes needed alibi-detect as well to be upgraded for python3.12 support. Please review and let me know for any changes.

**Comment by sergioave** [comment]
It would be quite a hassle to go directly to the support up to version 3.13.

**Comment by Singhal-harsh** [comment]
Hi team, any update on this? We are working on a high priority project and are using mlserver for its asynchronous serving capabilities. We have to migrate to python 3.12 because of company policies and hence would love if this library supports 3.12.

**Comment by sakoush** [comment]
@Singhal-harsh, @shivakrishnaah has a draft PR: https://github.com/SeldonIO/MLServer/pull/1951 to add support for python 3.12.

However we realised  that we need to upgrade some of the internal libraries that mlserver is using (`alibi` and `alibi-detect`), which should be done before accepting #1951 

We are actively working to upgrade these deps to support python 3.12; as we have also other priorities I cant give an estimate at the moment when they are likely to be done though.

**Comment by BJohnBraddock** [comment]
It looks like `alibi` and `alibi-detect` have been successful upgraded to support Python 3.12. 

does that give MLServer the all clear to pull in 3.12 support?

**Comment by sakoush** [comment]
yes, ongoing work can be tracked in https://github.com/SeldonIO/MLServer/pull/1951

**Comment by sakoush** [comment]
https://github.com/SeldonIO/MLServer/pull/1951 is now merged. mlserver supports py3.9-py3.12. thanks @shivakrishnaah for providing help on this support.
