### ISSUE TITLE
pydantic and pydantic-settings dependency versions on PyPI not consistent with pyproject.toml in repo

### ISSUE THREAD

**Issue by uwu-420** [SeldonIO/MLServer#1948]
Hi, thanks for making mlserver!

I noticed that the release of mlserver on PyPI (https://pypi.org/project/mlserver/1.6.1/#files) does not reflect the dependency rules as stated in the repos pyproject.toml https://github.com/SeldonIO/MLServer/blob/1ce29e65d5cd14a24a573f2f44ae2eac2b51a0f4/pyproject.toml#L65C1-L66C29 when it comes to pydantic and pydantic-settings. The PyPI release requires strict version equality
```
Requires-Dist: pydantic (==2.7.1)
Requires-Dist: pydantic-settings (==2.2.1)
```
while the pyproject.toml in the repo doesn't
```
pydantic = "^2.7.1"
pydantic-settings = "^2.2.1"
```
That messes quite a bit with my project's dependencies. Is that strict equality necessary?

Cheers

**Comment by sakoush** [comment]
@uwu-420 relaxing pydantic requirements is a recent change from https://github.com/SeldonIO/MLServer/pull/1928 but it is not yet release. We dont have  a release date for next version unfortunately, but likely to be in the new few weeks.

**Comment by uwu-420** [comment]
Okay, thanks for the fast reply! :) Got it.
