### ISSUE TITLE
Support HTTPS for model downloading

### ISSUE THREAD

**Issue by ellistarn** [SeldonIO/MLServer#2]
Might be worth upstreaming this KFServing PR here: https://github.com/kubeflow/kfserving/pull/979

**Comment by adriangonz** [comment]
Hey @ellistarn @tduffy000 ,

Thanks for opening up this issue! 

I've been thinking lately about this particular point. Should the storage / downloading logic live within the inference server?  Currently, on both Seldon Core and KFServing, we perform the download on the init container. Thus, the logic is contained completely outside of the server itself. This becomes extra relevant with multi-model serving where it seems there will be some sort of "puller" doing the download across models.

Recently, in Seldon Core, we also decided to remove the cloud storage logic out of the Python wrapper to reduce the number of dependencies of the `seldon_core` package (https://github.com/SeldonIO/seldon-core/pull/2310). Instead, we just use the same image as KFServing for the model initialiser.
 
It would be great to get your thoughts on this! We should also bring this topic to the next WG meeting.

**Comment by ellistarn** [comment]
This is actually a great point. This logic should probably live in Bloomberg's model puller. Let's discuss at WG.

**Comment by adriangonz** [comment]
Closing this one as this is already supported in KFServing's agent.
