### ISSUE TITLE
[gRPC] Model outputs get ignored

### ISSUE THREAD

**Issue by aaad** [SeldonIO/MLServer#201]
Hi,

thank you for this nice project. I am using the following _go_ code to create a _gRPC_ request for accessing a sklearn model. In my understanding the model should use the predict_proba() method and return it as output "**predict_proba**", however I only get the output "**predict**" returned.

```
	return &pb.ModelInferRequest{
		ModelName: c.modelName,
		Outputs: []*pb.ModelInferRequest_InferRequestedOutputTensor{
			{
				Name: "predict_proba",
			},
		},
		Inputs: []*pb.ModelInferRequest_InferInputTensor{
			{
				Name:     c.modelName,
				Datatype: "FP32",
				Shape:    []int64{1, int64(len(profile))},
				Contents: &pb.InferTensorContents{
					Fp32Contents: profile,
				},
			},
		},
	}
```

If I add an output {Name:"**test**"} the code in https://github.com/SeldonIO/MLServer/blob/0936e26354a6df77c7692faaa9c9467f5f674573/runtimes/sklearn/mlserver_sklearn/sklearn.py should raise an InferenceError Exception in line 58 but this does not happen, I assume that payload.outputs is None. I have also tested adding another input, this leads to the Exception in Line 46. 

Am I setting the Outputs accordingly? How can I access sklearn's _predict_proba_ method?

**Comment by aaad** [comment]
I found out that the installed version by pip (**mlserver-0.3.2**) is aged and missing the outputs that has been added in the master's version. -> This can be closed, sorry for the inconvenience.

```

class ModelInferRequestConverter:
    @classmethod
    def to_types(cls, pb_object: pb.ModelInferRequest) -> types.InferenceRequest:
        return types.InferenceRequest.construct(
          [...]
            # TODO: Add ouputs,
        )

    @classmethod
    def from_types(
        cls, type_object: types.InferenceRequest, model_name: str, model_version: str
    ) -> pb.ModelInferRequest:
        return pb.ModelInferRequest(
          [...]
            # TODO: Add ouputs,
        )

```

**Comment by adriangonz** [comment]
Hey @aaad, good catch!

You're right in that this may be fixed in the current `master`. Although, just to verify, do you think you'd be able to try that out? Happy to have a look if we find that there's still an issue in `master`.

**Comment by aaad** [comment]
I have already tried it in the current `master`. Works like a charm, thanks again! :)

**Comment by adriangonz** [comment]
Awesome! Thanks for testing it out @aaad. In that case, I'll close this one.
