### ISSUE TITLE
Does MlServernow support grpc calls?

### ISSUE THREAD

**Issue by lianxmfor** [SeldonIO/MLServer#234]

**Comment by adriangonz** [comment]
Hey @lianxmfor, MLServer supports gRPC as well as REST. By default, both servers will start at the same time.

**Comment by lianxmfor** [comment]
Thank you, I am putting our conversation here so that more people with doubts can see it.

https://seldondev.slack.com/archives/C8Y9A8G0Y/p1626329435123100

**Comment by adriangonz** [comment]
Good idea @lianxmfor !

I think that the Seldon Community Slack is on the free plan, so just in case the message goes over the 1000 limit, MLServer exposes its gRPC server under port `8081` by default.

We'll keep this issue opened to take it into account for the documentation efforts.
