### ISSUE TITLE
Adaptive batching

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/MLServer#239]
Explore whether MLServer could include support for adaptive batching. That is, dynamically grouping incoming requests together into a single batch, so that we can leverage any vectorisation / optimisation in the underlying model.

**Comment by ntorba** [comment]
I recently came across a couple of implementations of this
* threaded example on flask: https://www.sicara.ai/blog/optimize-response-time-api (ML model in example)
* async example on FastAPI: https://levelup.gitconnected.com/fastapi-how-to-process-incoming-requests-in-batches-b384a1406ec (simple example, different use case)

I could see a combination of these 2 as a solution to this, but they're pretty vanilla implementations. I'm curious what your team has in mind for this (for example, what queue implementation would you use?)
