### ISSUE TITLE
pydantic missing from dependencies

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/MLServer#241]
Pydantic is used here:
https://github.com/SeldonIO/MLServer/blob/494632287c5c6f0e70f0052b4cd49cd71932ecce/mlserver/types/dataplane.py#L6

but missing from setup.py

**Comment by adriangonz** [comment]
Pydantic should be there through the `FastAPI` dependency. 

This is a good question though, if we use a library directly, should we list it in the `setup.py` explicitly even though it's a subdep of another dependency?

**Comment by adriangonz** [comment]
Closing as `pydantic` should be a transitive dep of `fastapi`
