### ISSUE TITLE
Support for PyTorch / TensorFlow models?

### ISSUE THREAD

**Issue by khushbuadav** [SeldonIO/MLServer#250]
Does MLServer support other platforms (specifically `PyTorch`/`TensorFlow`) models other than the ones listed [here](https://github.com/SeldonIO/MLServer#inference-runtimes)?

Can I use the [custom-inference-runtime](https://github.com/SeldonIO/MLServer/blob/master/docs/examples/custom/README.md#custom-inference-runtime) for this? Given the popularity of both the platforms, am surprised there are no mentions of this in issues/docs.
Thanks!

**Comment by adriangonz** [comment]
Hey @khushbuadav, there's currently no plan to add support for PyTorch / Tensorflow. Generally, these type of GPU-backed Deep Learning model frameworks are already supported by [Nvidia's Triton server](https://github.com/triton-inference-server/server), whereas MLServer is mainly focusing currently on other types of CPU-bound models.

The API exposed by both Triton and MLServer aligns with the standard [V2 Inference Protocol](https://github.com/kubeflow/kfserving/tree/master/docs/predict-api/v2), therefore you should be able to mix and match between both MLServer and Triton. 

However, regardless of the above, you are right in that it should be relatively straightforward to write a custom inference runtime which knows how to load and predict on PyTorch / Tensorflow models. Let us know if you want to take this approach. Happy to help out!

**Comment by khushbuadav** [comment]
Thanks @adriangonz. We looked at [Nvidia's Triton server](https://github.com/triton-inference-server/server), but liked the simplicity of `MLServer` the most. For now we will mostly try adding a custom runtime and leverage GPU from there.
