### ISSUE TITLE
gRPC demo sample

### ISSUE THREAD

**Issue by bangpc** [SeldonIO/MLServer#394]
Hello, I see that MLServer support gRPC however I can not find any sample about using gRPC. Can you provide sample to serving with gRPC protocol? Thank you!

**Comment by adriangonz** [comment]
Hey @bangpc , we don't currently have any examples with gRPC. We'll add that to the list. 

In the meantime though, if you're familiar with how gRPC works, then it should be possible to use the protobuf definitions in the [`./proto`](https://github.com/SeldonIO/MLServer/tree/master/proto) folder (particularly the [`inference.GRPCInferenceService/ModelInfer`](https://github.com/SeldonIO/MLServer/blob/477f7c53b1e93e0de5718d4818772292b02758a5/proto/dataplane.proto#L26) one), alongside [`grpcurl`](https://github.com/fullstorydev/grpcurl) to send requests. Alternatively, you can also check out the [gRPC tests](https://github.com/SeldonIO/MLServer/blob/477f7c53b1e93e0de5718d4818772292b02758a5/tests/grpc/test_servicers.py#L62) to see examples of how to use the generated gRPC stubs to send requests.

**Comment by bangpc** [comment]
Thanks @adriangonz for your quick response,
I have addition question about endpoint for both HTTP/REST and gRPC. I can not see any configurable option for both of them. 
- For HTTP/REST, I can send request to my server based on example provide by this repo
- For gRPC, I do not know how to send request to my server because I do not know what is the endpoint for gRPC server.

**Comment by adriangonz** [comment]
Right, the gRPC server is exposed on port `8081` by default. You can check the default settings and / or how to change the default value in the docs:

https://mlserver.readthedocs.io/en/latest/reference/settings.html#mlserver.settings.Settings.grpc_port

**Comment by bangpc** [comment]
Thank you very much!
