### ISSUE TITLE
MLServer cli install dev versions on local machine

### ISSUE THREAD

**Issue by Aggiemaster** [SeldonIO/MLServer#403]
Hi,
Im looking for documentation on how to install dev versions of the mlserver cli tool.

I wanted to use the newer command for `mlserver build` which looks like it was merged in 0.6.0.dev3, but the pip install will install 0.5.3.  

Any help is appreciated, thanks in advance!

**Comment by Aggiemaster** [comment]
I saw this from this PR by @adriangonz 

https://github.com/SeldonIO/MLServer/pull/371

**Comment by Aggiemaster** [comment]
Closing this issue.  I didnt see the version listed in pip install, but its there.

`pip install mlserver==0.6.0.dev3`

**Comment by adriangonz** [comment]
That's exactly right @Aggiemaster. It should be possible to force `pip` to install particular pre-release dev versions. 

Thanks for adding the note with the solution BTW. That will be really helpful for the next user who stumbles upon this one.
