### ISSUE TITLE
Command build not available 

### ISSUE THREAD

**Issue by oriolcmp** [SeldonIO/MLServer#414]
Hello,

I installed mlserver and when I tried to use it to create a docker image, I got the following message:

`Error: No such command 'build'`

Actually, when I do a` mlserver --help` I get that:

```
Usage: mlserver [OPTIONS] COMMAND [ARGS]...

  Command-line interface to manage MLServer models.

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  start  Start serving a machine learning model with MLServer.
```

**Comment by adriangonz** [comment]
Hey @oriolcmp, it seems that PyPi treats the latest '1.0.0.rc1' as a "dev build", and so it doesn't default to that one.

Could try installing MLServer as 'pip install mlserver==1.0.0.rc1'?

**Comment by oriolcmp** [comment]
Yes, it works now.
Thank you
