### ISSUE TITLE
ETA for 1.x releases?

### ISSUE THREAD

**Issue by njhill** [SeldonIO/MLServer#443]
Hi @adriangonz and team, we were wondering what your plans were for a "final" 1.x release since there are various improvements and fixes important to us not in the 0.5 releases (including #425 which will hopefully go in soon). Let us know if there's anything we can do to help with this, thanks!

**Comment by adriangonz** [comment]
Hey @njhill, that's a great question! 

A few weeks ago, we released our first "release candidate" (i.e. `1.0.0.rc1`), which already includes a few fixes. We're now tackling the last set of issues, and should be soon (within the next few weeks) releasing the final `1.0.0` (which would include all those final tweaks and fixes).

**Comment by njhill** [comment]
Thanks @adriangonz, that's great to hear! Would be eager to hear once you have a more precise target for the release date since we have some downstream products hoping to make use of MLServer but would like to be on a final release version (and they require the fixes that aren't in 0.5.x).
