### ISSUE TITLE
Tag model-specific Prometheus metrics

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/MLServer#457]
Prometheus metrics exposed by MLServer currently don't tag model-specific ones (e.g. request count, or request time), which could be useful to assess how each separate model is performing. It could be useful to tag them with a `model_name` (and `model_version`) label so that they can be traced back.

**Comment by cliveseldon** [comment]
Note Triton has following metrics

```
# HELP nv_inference_request_success Number of successful inference requests, all batch sizes
# TYPE nv_inference_request_success counter
nv_inference_request_success{model="iris",version="1"} 4.000000
# HELP nv_inference_request_failure Number of failed inference requests, all batch sizes
# TYPE nv_inference_request_failure counter
nv_inference_request_failure{model="iris",version="1"} 0.000000
# HELP nv_inference_count Number of inferences performed
# TYPE nv_inference_count counter
nv_inference_count{model="iris",version="1"} 4.000000
# HELP nv_inference_exec_count Number of model executions performed
# TYPE nv_inference_exec_count counter
nv_inference_exec_count{model="iris",version="1"} 4.000000
# HELP nv_inference_request_duration_us Cummulative inference request duration in microseconds
# TYPE nv_inference_request_duration_us counter
nv_inference_request_duration_us{model="iris",version="1"} 16233.000000
# HELP nv_inference_queue_duration_us Cummulative inference queuing duration in microseconds
# TYPE nv_inference_queue_duration_us counter
nv_inference_queue_duration_us{model="iris",version="1"} 319.000000
# HELP nv_inference_compute_input_duration_us Cummulative compute input duration in microseconds
# TYPE nv_inference_compute_input_duration_us counter
nv_inference_compute_input_duration_us{model="iris",version="1"} 569.000000
# HELP nv_inference_compute_infer_duration_us Cummulative compute inference duration in microseconds
# TYPE nv_inference_compute_infer_duration_us counter
nv_inference_compute_infer_duration_us{model="iris",version="1"} 14489.000000
# HELP nv_inference_compute_output_duration_us Cummulative inference compute output duration in microseconds
# TYPE nv_inference_compute_output_duration_us counter
nv_inference_compute_output_duration_us{model="iris",version="1"} 403.000000
```

I don't see any differentiation between grpc and REST.

**Comment by PaulEdwardBrennan** [comment]
Can you explain what it means to "tag" a Prometheus metric? Do you mean tag as per cliveseldon's comment above on the 27th Jan?

Also, can you please provide an indication as to where in the code this tagging would be done? Where are the Prometheus metrics assembled?

**Comment by adriangonz** [comment]
Hey @PaulEdwardBrennan , sure thing.

At the moment, the metrics get collected at two main points:

- On the REST server, the middleware added by `starlette_exporter` will collect metrics for each incoming REST request: https://github.com/SeldonIO/MLServer/blob/49e1bcdf0679620568954a69234a311a8a1f451f/mlserver/rest/app.py#L117-L129
- Likewise, on the gRPC server, the interceptor provided by `py_grpc_prometheus` will collect metrics for gRPC requests: https://github.com/SeldonIO/MLServer/blob/49e1bcdf0679620568954a69234a311a8a1f451f/mlserver/grpc/server.py#L38

In both cases, these interceptors / middlewares will collect and generate a set of metrics automatically (i.e. by capturing each incoming request). Ideally, we should be able to add custom tags to these metrics without going too deep on the implementation of each library. So this may require a bit of research to see what options do these frameworks expose to customise the metrics that they generate.

**Comment by PaulEdwardBrennan** [comment]
Thanks for the reply, Adrian.

I've done a bit of digging today and I found the collection points for REST
and gRPC you mention above. It's good to have the confirmation from you.

I have more work to do but it seems:
   - On the gRPC side it's more open and I think we can add in extra labels
to the Prom metrics objects easily enough.
   - One the REST side, however it seems that starlette-explorer handles
the Prom metrics and just outputs some basic labels. It doesn't look like
you can add extra labels. There is mention of a custom handler in the docs
which I need to investigate.

Paul.

**Comment by adriangonz** [comment]
Just as an update on this one, #560 has added a new set of metrics (all tagged with `model` and `version`):

- `model_infer_request_success`
- `model_infer_request_failure`
- `model_infer_request_duration`
