### ISSUE TITLE
Error failed to load model from model_dir

### ISSUE THREAD

**Issue by Suresh-Nakkeran** [SeldonIO/MLServer#465]
The xgboost models from `model_dir` are not loading, throws an error `Invalid model uri provided`. It's working if we provide `model_uri`. The sklearn model are loading properly without `model_uri`.
xgboost model: [gs://seldon-models/sklearn/mms/lr_model](url)
sklearn model: [gs://kfserving-samples/models/xgboost/iris](url)

![Screenshot from 2022-02-01 00-02-27](https://user-images.githubusercontent.com/30799624/152108125-2a0ddee3-867f-4dc2-94ab-293e257348a1.png)

**Comment by adriangonz** [comment]
Hey @Suresh-Nakkeran ,

As discussed in Slack, my guess is that since there isn't a `model-settings.json` file in the XGBoost folder, MLServer can't find that model. 

Do you know whether the new KServe operator injects a `model-settings.json` config on the fly?

**Comment by adriangonz** [comment]
Hey @Suresh-Nakkeran, if I recall correctly, this was already sorted out, right? I'll be closing it down, but feel free to reopen if this is still an issue.
