### ISSUE TITLE
Add support for predict_proba in XGBoost inference runtime

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/MLServer#475]
Currently, the XGBoost runtime only supports the `predict()` method. On top of this one, it would be useful to also add support for the [`predict_proba()` one](https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.XGBClassifier.predict_proba), similar to how the SKLearn runtime works.

**Comment by shane-breeze** [comment]
The `xgboost.Booster.predict` method used in the XGBoost runtime already returns values similar to `predict_proba` (i.e. probabilities and not predictions).

If the user wants to use the `xgboost.sklearn.XGBClassifier` interface, they can always save their `XGBClassifier` with joblib and use the "mlserver_sklearn.SKLearnModel` interface.
