### ISSUE TITLE
Add support for raw_input_contents field

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/MLServer#48]
Add support for top-level `raw_input_contents` in gRPC spec. This field was initially introduced to work-around some performance issues within gRPC.

You can find more details on these issues: 

- https://github.com/triton-inference-server/server/issues/1821
- https://github.com/kubeflow/kfserving/pull/998

**Comment by LuBingtan** [comment]
Any updates ?

**Comment by adriangonz** [comment]
Hey @LuBingtan , this is prioritised on our internal roadmap but haven't gotten around it yet. 

Is this currently a blocker for you? Would be good to learn more about how it's affecting you.

**Comment by divyadilip91** [comment]
Hi @adriangonz 
Can we pass a raw input json to the ML server instead of the predefoned inference request format via seldon core deployment similar to the predict_raw method in seldon core that accepts a raw json?

**Comment by adriangonz** [comment]
Hey @divyadilip91, it's possible to define custom endpoints within a custom inference runtime. This is not currently documented, but you can see [an example in the MLflow runtime](https://github.com/SeldonIO/MLServer/blob/aa1fd2ab59dc3bbfdafa662e9b8c0485aea7c838/runtimes/mlflow/mlserver_mlflow/runtime.py#L44-L55).

Just for extra context though, this issue is not about custom payloads, but allowing the user to send a _compact_ binary representation of their V2 payload (which can reduce latency in some use cases).

**Comment by divyadilip91** [comment]
Thankyou @adriangonz
