### ISSUE TITLE
[WARNING] Model is different than model's folder name

### ISSUE THREAD

**Issue by kurianbenoy-sentient** [SeldonIO/MLServer#532]
What does the warning in MLserver signify with the below message:

```
2022-03-23 07:44:01,202 [mlserver] WARNING - Model name 'Enmltrans' is different than model's folder name '.'.
```

My file structure is as follows:

```
(env) kurianbenoy@kurianbenoy-VirtualBox:~/MLServer/microservice-ai-en_ml_translation_mlserver$ ls -la
total 56
drwxrwxr-x 5 kurianbenoy kurianbenoy  4096 Mar 23 07:44 .
drwxrwxr-x 4 kurianbenoy kurianbenoy  4096 Mar 23 07:09 ..
drwxrwxr-x 6 kurianbenoy kurianbenoy  4096 Mar 23 07:10 env
drwxrwxr-x 8 kurianbenoy kurianbenoy  4096 Mar 23 07:16 .git
-rw-rw-r-- 1 kurianbenoy kurianbenoy  1799 Mar 23 07:09 .gitignore
-rw-rw-r-- 1 kurianbenoy kurianbenoy 11357 Mar 23 07:09 LICENSE
-rw-rw-r-- 1 kurianbenoy kurianbenoy    66 Mar 23 07:43 model-settings.json
-rw-rw-r-- 1 kurianbenoy kurianbenoy  1151 Mar 23 07:36 models.py
drwxrwxr-x 2 kurianbenoy kurianbenoy  4096 Mar 23 07:44 __pycache__
-rw-rw-r-- 1 kurianbenoy kurianbenoy    46 Mar 23 07:09 README.md
-rw-rw-r-- 1 kurianbenoy kurianbenoy    92 Mar 23 07:11 requirements_prod.txt
```

**Comment by adriangonz** [comment]
Hey @kurianbenoy-sentient ,

Good point!

That warning is mostly relevant for the case where the model name comes from an upstream serving engine, like Seldon Core or KServe. In those cases, the `model-settings.json` file will usually have no name, and it will be inferred instead from the folder's name. The "edge case" would come when there's a `model-settings.json` file present, listing a different model name. In those cases, we'll go ahead with what the model says and just flag it in the logs.

In the base use case of just serving a model locally, it can be safely ignored though.

Does this help to clarify your question @kurianbenoy-sentient ?

**Comment by kurianbenoy-sentient** [comment]
I see. It clarifies my question @adriangonz
