### ISSUE TITLE
MLServer not working with deployments options with Ambassador, seldon-core

### ISSUE THREAD

**Issue by kurianbenoy-sentient** [SeldonIO/MLServer#549]
I have been trying to deploy a micro service we developed to use with MLServer. We have been deploying it previously with `seldon-core` and we are using `ambassador` as well.

`seldon_deployment.yaml` file is given below:

```code
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: enmltranslation 
spec:
  protocol: kfserving
  annotations:
    project_name: enmltranslation
    deployment_version: v0.1.0
    seldon.io/rest-timeout: '60000'
    seldon.io/rest-connection-timeout: '60000'
    seldon.io/grpc-read-timeout: '60000'
    seldon.io/ambassador-config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: enmltrans_mapping_v0.1.0
      prefix: /microservices/nlp/enmltrans/v0/getpredictions
      service: enmltranslation-pod.default:8000
      rewrite: /nlp/enml/predictions

  predictors:
    - name: default
      graph:
        name: manglish-model 
        type: MODEL
      componentSpecs:
        - spec:
            containers:
              - name: manglish-model  
                image: manglishdummy:v0.1.0 
                ports:
                  - containerPort: 8080
                    name: http
                    protocol: TCP
                  - containerPort: 8081
                    name: grpc
                    protocol: TCP
```

When accessing the URL via ambassador we are 503 HTTP error indicating service is unavailable.

**Update: (April 1, 2022)**

I was able to bring up a normal kubernetees deployment by following a [`deployment.yaml` similar to the one provided in tutorial.](https://mlserver.readthedocs.io/en/latest/examples/custom/README.html#deploying-our-custom-image) Yet ambassador support for MLServer seems not working at the moment.

**Update (April 20, 2022)**

With help of @adriangonz solution, by passing no-executors in seldon-core we are now able to customize the URL with ambassador. Yet is it possible without by passing `no-executors` so that we can avail the seldon-core's graph functionality?

**Comment by adriangonz** [comment]
Hey @kurianbenoy-sentient ,

If you remove the `seldon.io/ambassador-config` entry from the annotations of your `SeldonDeployment` manifest, then Seldon Core should be able to figure out the right config to create. I'm wondering whether the config that you've added there may be causing any conflict. Would you be able to try that out @kurianbenoy-sentient ?

Besides the above, @kurianbenoy-sentient could you provide more details of:

- What endpoint are you using to hit your model?
- Is the pod running correctly?
- Has Seldon Core been installed correctly with Ambassador support? 
- Is your Ambasador set up leveraging the [new Ambassador Edge stack](https://www.getambassador.io/products/edge-stack/), which is [not supported yet in Seldon Core](https://github.com/SeldonIO/seldon-core/issues/3872)?

PS: @kurianbenoy-sentient given that this feels more like an issue at the Seldon Core / Ambassador level (rather than MLServer's), you may be able to get further help raising it on the https://github.com/SeldonIO/seldon-core repo (or [Seldon slack](https://join.slack.com/t/seldondev/shared_invite/zt-vejg6ttd-ksZiQs3O_HOtPQsen_labg)) instead.

**Comment by kurianbenoy-sentient** [comment]
> If you remove the `seldon.io/ambassador-config` entry from the annotations of your `SeldonDeployment` manifest, then Seldon Core should be able to figure out the right config to create. I'm wondering whether the config that you've added there may be causing any conflict. Would you be able to try that out @kurianbenoy-sentient ?
> 

We tried after removing seldon.io/ambassador-config from annotations of `seldonDeployment`, using the modified seldon-deployment file as [follows in given link](https://gist.github.com/kurianbenoy-sentient/0cc7ae9c153b66a68cfdaf383018b00f).


> Besides the above, @kurianbenoy-sentient could you provide more details of:
> 
>     * What endpoint are you using to hit your model?
> 

We are trying to use the model by using custom_methods, instead of the default predict method in MLServer/seldon-core.


>     * Is the pod running correctly?
> 
Yes, the pod is runing correctly with no errlersn i,kambassador config
>     * Has Seldon Core been installed correctly with Ambassador support?
> 
Yes
>     * Is your Ambasador set up leveraging the [new Ambassador Edge stack](https://www.getambassador.io/products/edge-stack/), which is [not supported yet in Seldon Core](https://github.com/SeldonIO/seldon-core/issues/3872)?

Nowe are using Ambassador with a version supported by seldon-core

**Comment by kurianbenoy-sentient** [comment]
@adriangonz  we tried with the endpoint: `http://host/seldon/default/enmltranslation-v0-1-0/nlp/enml/predictions`. 

Inorder to by pass the executor what needs to be done? In normal seldon-core due to this issue, we are actually using annotations with rewrite:

```
    seldon.io/ambassador-config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: enmltrans_mapping_v0.1.0
      prefix: /microservices/nlp/enmltrans/v0/getpredictions
      service: enmltranslation-pod.default:8000
      rewrite: /nlp/enml/predictions
```

**Comment by adriangonz** [comment]
Hey @kurianbenoy-sentient, you can find more info on bypassing the executor in the Seldon Core docs:

https://docs.seldon.io/projects/seldon-core/en/latest/graph/svcorch.html#bypass-service-orchestrator-version-0-5-0

I'd try that first, removing the Ambassador annotation. Mainly to avoid getting side effects.

**Comment by kurianbenoy-sentient** [comment]
Today after bypassing the executor in seldon core, by following the link you shared. We were able to access our custom API endpoint via ambassador with the url `/seldon/<namespace>/<model-name>/nlp/enml/predictions`.

@adriangonz  We want to have the abilitiy to rewrite the endpoint from `/seldon/<namespace>/<model-name>/nlp/enml/predictions` to a custom endpoint in ambassador like `/microservices/<url>`. Is it possible?

**Comment by kurianbenoy-sentient** [comment]
We were able to customize the URL in ambassador, by using no-executors with the below configuration.  Yet is it possible without by passing no-executors so that we can avail the seldon-core's graph functionality?

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: enmltranslation
  labels:
    model_name: enmltranslation
spec:
  name: enmltranslation
  annotations:
    seldon.io/ambassador-config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: enmltrans_mapping_v0.1.0
      prefix: /microservices/nlp/enmltrans/v0/getpredictions
      service: enmltranslation-pod.default:8080
      rewrite: /nlp/enml/predictions
  predictors:
  -  annotations:
       seldon.io/no-engine: "true" 
...
...
```

**Comment by adriangonz** [comment]
Hey @kurianbenoy-sentient , 

On the question about the URL rewrite, I'm not an expert on Ambassador, but perhaps the Ambassador community may be better at answering that one?

On the second one, if you disable the executor you will lose the graph functionality on that particular model. The problem with custom endpoints is that the model's requests and responses become a black box, so there's no way for the Seldon Core executor to know how to chain them, and propagate them through the graph.  

Given that the pending remaining issues seem to be related to other projects (i.e. Ambassador and Seldon Core), I'll be closing this ticket. Feel free to open up a new one if you find any other MLServer issue or if you've any extra questions.
