### ISSUE TITLE
MLServer to hide http health request logs to avoid polluting the logs

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/MLServer#553]
As part of the Seldon Core addition https://github.com/SeldonIO/seldon-core/pull/4028 which moves the TCP ready checks into proper HTTP request ready checks to `v2/health/ready` there is now a lot of noise from the readiness checks every 5 seconds. We should explore ways in which we avoid this noise, perhaps making it completely silent by default, or eventually once the prometheus server is created on a separate server this could also be added (And both of  them could be muted)

![image](https://user-images.githubusercontent.com/1447507/161749439-3e96c417-a630-4208-80d6-5fc5f262fcd3.png)

**Comment by saeid93** [comment]
@axsaucedo have you found a solution to this? I also cannot read the logs.
