### ISSUE TITLE
[Protobuf] TypeError: Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by jakob-ed** [SeldonIO/MLServer#615]
We get this error on startup of the inference server with `mlserver==1.0.1` so that the server is completely blocked from working on requests. 

```
Traceback (most recent call last):
  File "/usr/local/bin/mlserver", line 5, in <module>
    from mlserver.cli import main
  File "/usr/local/lib/python3.8/site-packages/mlserver/__init__.py", line 2, in <module>
    from .server import MLServer
  File "/usr/local/lib/python3.8/site-packages/mlserver/server.py", line 15, in <module>
    from .grpc import GRPCServer
  File "/usr/local/lib/python3.8/site-packages/mlserver/grpc/__init__.py", line 1, in <module>
    from .server import GRPCServer
  File "/usr/local/lib/python3.8/site-packages/mlserver/grpc/server.py", line 8, in <module>
    from .servicers import InferenceServicer, ModelRepositoryServicer
  File "/usr/local/lib/python3.8/site-packages/mlserver/grpc/servicers.py", line 5, in <module>
    from . import dataplane_pb2 as pb
  File "/usr/local/lib/python3.8/site-packages/mlserver/grpc/dataplane_pb2.py", line 25, in <module>
    _SERVERLIVEREQUEST = _descriptor.Descriptor(
  File "/usr/local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 313, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by adriangonz** [comment]
Hey @jakob-ed ,

Is this from a custom Docker image built with `mlserver build .`? From the looks of it, it seems there may be two versions of MLServer clashing between them. 

Also, could you try with `mlserver==1.1.0.dev6` instead? This is our latest nightly build.

**Comment by jakob-ed** [comment]
Hi, thanks for getting back so quickly! We are running MLServer in a docker image but we don't use `mlserver build .`. I don't see a way how there could be multiple versions of MLServer clashing with each other in our setup. We only have `mlserver` and another dependency (which doesn't depend on mlserver itself). Dockerfile is also very basic. 

However, everything works fine with `mlserver==1.1.0.dev6`.

**Comment by adriangonz** [comment]
Hey @jakob-ed ,

After having a deeper look into this one, I can confirm that we can replicate the same on our end. That is, running the `mlserver` CLI directly when installing `mlserver==1.0.1`, ends on the error above. 

The `grpcio` package is not bounded atm, and that seems to have caused this issue. Therefore, a temporary workaround would be to also install `grpcio==3.20.1`, as in:

```
pip install mlserver==1.0.1 grpcio==3.20.1
```

Given that we should be releasing MLServer `1.1.0` next week (hopefully :crossed_fingers:), and that `1.1.0` fixes this issue, would it still make sense to release a `1.0.2` fix of the above?

**Comment by illeatmyhat** [comment]
Updating to `1.1.0` didn't solve this problem for us. The error still occurs at inference time.
The solution was to add a version guard `protobuf<4.0.0`

**Comment by kushan-gunasekera** [comment]
For anyone who is looking for a proper solution.

https://stackoverflow.com/a/72493690/6194097

**Comment by adriangonz** [comment]
Hey everyone,

Following up on this one, we haven't been able to replicate any issues with `mlserver == 1.1.0`. 

@illeatmyhat would you be able to share the output of `pip freeze`?

**Comment by adriangonz** [comment]
Thanks for sharing those @illeatmyhat .  

That's strange. That set of deps is not too different from what I'm trying with `protobuf==4.21.2`, and I'm unable to replicate on my end.

I'm wondering whether this was just due to a particular version within the `4.x` branch of `protobuf`, which may have now been fixed. Would you be able to install `protobuf==4.21.2` to see if you can still see the same issue?
