### ISSUE TITLE
Worker doesn't pickup requests when using MLServer parallel inference

### ISSUE THREAD

**Issue by deli816** [SeldonIO/MLServer#642]
Hi,

I encountered a performance issue with MLServer when trying to serve a mlflow model.
Here are my environment variables and I didn't use the settings.json
```
MLSERVER_MODEL_IMPLEMENTATION=mlserver_mlflow.MLflowRuntime
MLSERVER_MODEL_PARALLEL_WORKERS=4
MLSERVER_MODEL_URI=model
MLSERVER_PARALLEL_WORKERS=4
MLSERVER_MODEL_NAME=default
```
After starting the server, I see there were multiple processes being created
```
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0 21 04:16 ?        00:34:04 /opt/conda/envs/mlflow-env/bin/python3.9 /opt/conda/envs/mlflow-env/bin//mlserver start home
root           5       1  0 04:16 ?        00:00:00 /opt/conda/envs/mlflow-env/bin/python3.9 -c from multiprocessing.resource_tracker import main;main(14)
root           6       1  0 04:16 ?        00:00:01 /opt/conda/envs/mlflow-env/bin/python3.9 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=15, pipe_handle=21) --multiprocessing-fork
root           7       1  0 04:16 ?        00:00:02 /opt/conda/envs/mlflow-env/bin/python3.9 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=15, pipe_handle=25) --multiprocessing-fork
root           8       1  0 04:16 ?        00:00:01 /opt/conda/envs/mlflow-env/bin/python3.9 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=15, pipe_handle=29) --multiprocessing-fork
root           9       1  0 04:16 ?        00:00:01 /opt/conda/envs/mlflow-env/bin/python3.9 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=15, pipe_handle=33) --multiprocessing-fork
```

However, when I sent parallel requests to the server, it seems all the requests were handled by the main mlserver process, while the others are idle. The requests did succeed though, so the server was functioning.
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND  PPID
      1 root      20   0 1662248 121124     52 R  97.0  0.7  31:35.43 mlserver    0
      5 root      20   0   26308   5368      4 S   0.0  0.0   0:00.04 python3.9   1
      6 root      20   0  628088 119340     12 S   0.0  0.7   0:01.97 python3.9   1
      7 root      20   0  628096 119324     12 S   0.0  0.7   0:02.04 python3.9   1
      8 root      20   0  628088 119288     12 S   0.0  0.7   0:01.90 python3.9.  1
      9 root      20   0  628088 119424     12 S   0.0  0.7   0:01.97 python3.9   1
```

Is there some settings that I missed?

**Comment by adriangonz** [comment]
Hey @deli816 ,

What version of MLServer are you using atm? From what I can see it seems that you're on `1.0`? There've been some improvements to parallel inference in `1.1`, so maybe it would be worth if you could try those out?

Having said that, if your model is not too compute intensive, it could be that the workers don't really get too hot (and that serialisation / deserialisation takes the most of the CPU usage).  To account for that, if your model is compatible with large batches, you could explore playing with the adaptive batching settings so that you make better usage of the workers' resources.

**Comment by deli816** [comment]
Hi @adriangonz. Thanks for your reply! I'm using the latest MLServer 1.1. Yes, the model is not compute intensive. Could you elaborate what is accounted for the serialization / deserialization in the master process? Is it the codec for transforming the payload into model framework compatible formate or just the serialization for payload json into InferenceRequest? For reference, in my case above, the payload is quite small and simple, it only contains 12 features each one is a single FP32. So I guess process the request payload shouldn't take a lot of CPU?

On a side note, I did try a more complex CNN model, while observing the workers CPU utilization is increased however not all workers are assigned with jobs. This also seems to indicate the master process is the bottle neck distributing the work to the wokers?
![Screen Shot 2022-06-24 at 2 31 45 PM](https://user-images.githubusercontent.com/21182197/175887240-edadd3e1-2e55-4f52-9c5f-a2c3ad22df31.png)

**Comment by adriangonz** [comment]
Hey @deli816 ,

Thanks for trying out with a diff model. Those results are interesting. 

There's something we noticed recently in #643 , which could be related to this one. Although I'm not still 100% clear whether that will improve things or not. We're planning to get this one sorted for a `1.1.1` release, so hopefully we'll have something soon to test the difference.

**Comment by deli816** [comment]
Hi @adriangonz,

Providing some update on this. When I was testing MLServer, I was using the mlflow "/invocations" endpoint. I think the handler for that runs on single process and it doesn't use the worker loop. That's why I only see the main thread handles busy while workers are idling. Sorry for being no clear on this! Is there a plan to make mlflow endpoint also utilize mutiprocessing?

On the other side. when testing the v2 endpoints, I do see the workers are picking up the request. And as you suggested with batching, the simple model do get performance boost, but complex model does not benefit from this, possibly due to the complex payload causing no enough request to distribute.

Not sure if you guys has benched marked MLServer against MLflow, if you have some material to share, it would be great.

**Comment by adriangonz** [comment]
Hey @deli816 ,

Thanks for that update.

That makes a lot of sense. As you say, only the `/v2/models/.../infer` calls get currently handled in the worker pool. For the next release of MLServer, we're planning to run every model-related call in the worker pool (caching the ones who won't change, like fetching the model metadata). So hopefully that should make it work seamlessly with the `/invocations` endpoint.

On the last point, do you mean against MLflow's built-in scoring server?

**Comment by deli816** [comment]
Hi @adriangonz ,

Thanks for your replay. Do you have an estimate timeline for the model related call using worker pool? or maybe an issue to track it? This would be greatly beneficial for existing mlflow users migrating to mlserver without performance degradation.

Yes, benchmark MLServer against MLflow built-in scoring server.

**Comment by adriangonz** [comment]
We don't currently have any benchmarks between the previous scoring server within MLflow and MLServer. However, it would be great if you managed to run some comparison. We'd be very keen to see the results. 

Currently, MLServer is also offered as an alternative within the MLflow CLI (through the `--enable-mlserver` flag). Therefore, it would be really useful to confirm whether MLServer is faster or not (which would be expected though). 

Since we have managed to validate that the original issue you mentioned will be covered by #601, I'll close this issue. Do keep an eye out in #601 though! It would be great to get some feedback once we have that one implemented.
