### ISSUE TITLE
Serve MLflow models without a model signature

### ISSUE THREAD

**Issue by deli816** [SeldonIO/MLServer#661]
Hi, is model signature required for using the MLServer-MLflow runtime? Seems for models that don't have a signature defined in the MLmodel, MLServer will have a hard time converting the v2 protocol payload into the mlflow input as there isn't a default codec. What's the recommended approach here? Thanks!

**Comment by adriangonz** [comment]
Hey @deli816 ,

The simplest approach is probably to have a MLflow model signature saved within your MLflow model. Most of the time this can be done automatically by MLflow. From this signature, MLServer can infer how it should treat each of the input fields (e.g. as a dataframe, as a tensor, etc.). 

If that's not present, you can also specify on each request and each input how should MLServer treat those. This is done through the [Content Types extension](https://mlserver.readthedocs.io/en/latest/user-guide/content-type.html) of the V2 Inference Protocol.

**Comment by adriangonz** [comment]
Hey @deli816,

Since the question seems answered, I'll close this down. Feel free to reopen if you're still facing any issues though.
