### ISSUE TITLE
[FR] Return the name or ID of the model artifact when running inference

### ISSUE THREAD

**Issue by dingobar** [SeldonIO/MLServer#709]
It would be useful for traceability to be able to know exactly which model a prediction came from. A use-case for this would be:
- I have a model called `my-model` deployed with mlserver
- I change the internal implementation of `my-model` (or re-train it or whatever) and re-deploy it
- The client services still use the same old endpoint, but underneath my new model is running
- **If the model ID was returned, the client could trace each prediction down to a single model artifact, be it an mlflow model or something else**

Another use-case:
- I have two different models running, `main` and `challenger`
- The client is set up to make daily inference with both of them and compares which is better
- The implementation of `challenger` changes over time
- After some time the client wants to go back and see exactly which model performed best, and trace it all the way back to the model artifact or even back to the code and the training data itself

Do anyone else have a similar use-case?

## Potential solution

- We return a header with some metadata, ie. `mlserver-model-id: my-model-123` when we run inference
- We make this configurable and disabled by default so that we don't risk exposing any secret information for users. Something like `MLSERVER_EXPOSE_MODEL_ID_HEADER=1` I guess?
- The model ID is inferred from the `parameters.uri` key in `model-settings.json`, or if that fails or doesn't exist, the model name

**Let me know what you think!**

PS. I can potentially help implement it.

**Comment by adriangonz** [comment]
Hey @dingobar ,

Thanks for opening this one! It's always great to hear feedback and ideas about new features. 

In this case, would the model ID be different from the combination of model name and model version?

**Comment by dingobar** [comment]
> Hey @dingobar ,
> 
> Thanks for opening this one! It's always great to hear feedback and ideas about new features. 
> 
> In this case, would the model ID be different from the combination of model name and model version?

I that's probably enough, if combined with the git history one can definitely dig out the reference to the artifact itself that way so that'd di nicely.

What do you think of the use-case?

**Comment by dingobar** [comment]
My particular use-case, which I guess can be generalized somewhat, is that I'd like to relate predictions to an mlflow model. I created a FR over at mlflow about it: https://github.com/mlflow/mlflow/issues/6657

**Comment by adriangonz** [comment]
Hey @dingobar ,

Thanks for the extra context.

I think the use case makes a lot of sense. Thinking about it though, aren't the `model_name` and `model_version` fields already returned in the inference response payload?
