### ISSUE TITLE
missing mentioning pushing image to the docker registry in the "serving custom model page"

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/MLServer#712]
Pushing the built docker container to a docker registry is not mentioned after the build process in [Serving a custom model](https://mlserver.readthedocs.io/en/latest/examples/custom/README.html). In my case, it was necessary but I wasn't sure if this is a generalizable case to add this as a pull request. If necessary I can add an extra step to the notebook for pushing to the container registry step.

**Comment by adriangonz** [comment]
Hey @saeid93 ,

That's a great point.

I agree with you though, in that it's not that generalizable. For starters, we would need to know the Docker Hub repo and image name that the user wants to use. 

What we could do instead, is to add a "Note block" clarifying that Seldon Core may expect that the image is available on Docker Hub or an alternative Docker registry and therefore the user may need to push it there?
