### ISSUE TITLE
PandasCodec unexpected behavior

### ISSUE THREAD

**Issue by pablobgar** [SeldonIO/MLServer#737]
Hi,

I am having some problems with PandasCodec and grpc requests.

On the client side, I have the following code to send a pandas df:

``` python

data = pd.DataFrame(data={'col1': ["test_string", "test_string"], 'col2': ["test_string", "test_string"]})

i_request = PandasCodec.encode_request(data)
i_request.parameters = types.Parameters(content_type="pd")

inference_request_g = converters.ModelInferRequestConverter.from_types(
    i_request, model_name=model_name, model_version=None
)

grpc_channel = grpc.insecure_channel("localhost:8081")
grpc_stub = dataplane.GRPCInferenceServiceStub(grpc_channel)
response = grpc_stub.ModelInfer(inference_request_g)

```

And I have this code fragment to receive it on the server side:

```` python

async def predict(self, payload: types.InferenceRequest) -> types.InferenceResponse:

        if payload.parameters.content_type == "pd":
            inference_data = PandasCodec.decode_request(payload)

            print(inference_data)

````

I get this output:

```` python
             col1            col2
0  b'test_string'  b'test_string'
1  b'test_string'  b'test_string'
````

The same dataframe, but with binary strings. I was expecting to get as a result the same dataframe that I have in the client, since I am using the same codec for encoding and decoding.

Is this an expected behavior? Maybe I am doing something wrong?

Thanks for your help.

**Comment by pablobgar** [comment]
Hi @adriangonz

Thanks for your fast response!!

This is the content of i_request:

```` python
{'id': None, 'parameters': {'content_type': 'pd', 'headers': None}, 'inputs': [{'name': 'col1', 'shape': [2], 'datatype': 'BYTES', 'parameters': None, 'data': [b'test_string', b'test_string']}, {'name': 'col2', 'shape': [2], 'datatype': 'BYTES', 'parameters': None, 'data': [b'test_string', b'test_string']}], 'outputs': None}
````

And this is inference_request_g:

````` python

model_name: "test"
parameters {
  key: "content_type"
  value {
    string_param: "pd"
  }
}
inputs {
  name: "col1"
  datatype: "BYTES"
  shape: 2
  contents {
    bytes_contents: "test_string"
    bytes_contents: "test_string"
  }
}
inputs {
  name: "col2"
  datatype: "BYTES"
  shape: 2
  contents {
    bytes_contents: "test_string"
    bytes_contents: "test_string"
  }
}

````

**Comment by adriangonz** [comment]
Hey @pablobgar ,

Right, that seems aligned with what was described on my comment above. The `PandasCodec.encode_request` method is not setting the right content type at the individual input level. 

Could you try explicitly setting `str` as the content type for the inputs of `i_request`? As in,

```python
from mlserver.codecs import StringCodec

for input in i_request.inputs:
	input.parameters = Parameters(content_type=StringCodec.ContentType)
```

**Comment by pablobgar** [comment]
This is the resulting request:

```` python

model_name: "arte"
parameters {
  key: "content_type"
  value {
    string_param: "pd"
  }
}
inputs {
  name: "col1"
  datatype: "BYTES"
  shape: 2
  parameters {
    key: "content_type"
    value {
      string_param: "str"
    }
  }
  contents {
    bytes_contents: "test_string"
    bytes_contents: "test_string"
  }
}
inputs {
  name: "col2"
  datatype: "BYTES"
  shape: 2
  parameters {
    key: "content_type"
    value {
      string_param: "str"
    }
  }
  contents {
    bytes_contents: "test_string"
    bytes_contents: "test_string"
  }
}

````

But i have the same result on the server:

```` python
             col1            col2
0  b'test_string'  b'test_string'
1  b'test_string'  b'test_string'
````

**Comment by adriangonz** [comment]
Hey @pablobgar, 

Thanks for trying that out.

Instead of calling the `PandasCodec.decode_request(payload)` method directly, could you call the `self.decode_request(payload, default_codec=PandasCodec)` method instead? This method should ensure that each input gets decoded appropriately first .

**Comment by pablobgar** [comment]
Hi @adriangonz 

I have the same result with `self.decode_request`.

It seems that decoding is not performed in any case when the content type is bytes and PandasCodec is used.
https://github.com/SeldonIO/MLServer/blob/1.1.0/mlserver/codecs/pandas.py#L17-L19

**Comment by pablobgar** [comment]
Hi @adriangonz 

Now it is working correctly if I add `Parameters(content_type=StringCodec.ContentType)`. Maybe I did something wrong when I tested it a few days ago, or I didn't test the combination of adding this and use the `self.decode_request` method, sorry.

This is my code:
``` python
data = pd.DataFrame(
    data={
        "col1": ["test_string", "test_string"],
        "col2": ["test_string", "test_string"],
    }
)

i_request = PandasCodec.encode_request(data)
i_request.parameters = types.Parameters(content_type="pd")

for input in i_request.inputs:
    input.parameters = types.Parameters(content_type=StringCodec.ContentType)
```

But then where I see a problem is the `PandasCodec.encode_request()`. Shouldn't it add this parameter to columns that are strings automatically?

**Comment by adriangonz** [comment]
Hey @pablobgar ,

Thanks for the update!

On the last point, I totally agree. And TBH, the `PandasCodec` should also be able to decode strings. To put it another way, since it's the only which knows when a series should be encoded as a string, it should also be able to decode a bytes array into a string series. 

We'll keep this issue open to tackle this last point.
