### ISSUE TITLE
Prometheus Metrics definition is missing from the documentation

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/MLServer#798]
Although the meaning of the metrics is common sense, since they are different from the original Seldon metrics, I think it's worthwhile to have a similar page like [Seldon Metrics](https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html) for MLServer.
![Screenshot 2022-10-22 at 20 32 48](https://user-images.githubusercontent.com/6298780/197367548-693ad573-e25a-4613-adf9-41786e9dc1fa.png)

**Comment by adriangonz** [comment]
Fixed by #1020
