### ISSUE TITLE
Serving mlflow tensorflow pyfunc model?

### ISSUE THREAD

**Issue by tamis-laan** [SeldonIO/MLServer#808]
I'm trying to serve a mlflow pyfunc model in kserve that uses tensorflow under the hood saved in a mlflow tracking server and inthe  mlflow format. I'm following this tutorial:

https://kserve.github.io/website/0.9/modelserving/v1beta1/mlflow/v2/ 

However the inference with our model fails and says: `no module named tensorflow`. Inspecting the MLServer runtime container we don't see tensorflow being installed. 

I'm a bit confused about this, the mlflow model format includes a requirements file, I expected that the mlserver would install all required dependencies? 

Also I wonder if mlserver is able to serve pyfunc models?

**Comment by adriangonz** [comment]
Hey @tamis-laan ,

MLServer won't install the model's extra requirements on the fly. Therefore, to serve MLflow models, you will need to build your environment in advance (as a conda-pack tarball), and keep that next to your model artefacts. MLServer will then be able to read and load that environment tarball to inject your custom environment.

Main reason why is done this way, is that building the environment on-the-fly can generally take a lot of time and introduce a lot of latency. 

You can find below instructions on how to build this conda-pack environment from MLflow's `conda.yaml` file (the instructions link to the SC repo, but would also apply to KServe):

https://docs.seldon.io/projects/seldon-core/en/latest/servers/mlflow.html#v2-protocol
