### ISSUE TITLE
Make pandas requirement optional?

### ISSUE THREAD

**Issue by dconathan** [SeldonIO/MLServer#837]
Is it possible to remove the dependency on `pandas` and make it optional? i.e. only register the `PandasCodec` if pandas is installed?  Pandas is a large dependency (e.g., adds >50mb to the build) that some users may not need.

**Comment by adriangonz** [comment]
Hey @dconathan ,

While possible, it's certainly not trivial. Is the extra `pandas` dep creating any blockers for you?

**Comment by dconathan** [comment]
Okay thanks. No particular blocker. I just don’t need pandas for my current project and I like to keep to keep my builds as small/fast as possible!

Is this something you’d consider a PR for or do you think the downstream complexity wouldn’t be practical?
