### ISSUE TITLE
Request to support ONNX model loading in MLServer for huggingface

### ISSUE THREAD

**Issue by bugzyz** [SeldonIO/MLServer#852]
Hi, there!

We are recently using seldon deployment with huggingface mlserver. For our use case, we already downloaded the model from huggingface hub and placed it in a certain directory for loading. Currently, it's in huggingface(pytorch_model.bin?) format which is the most of the case in huggingface hub. And now, we would like to provide the model to mlserver in ONNX format as we want to do some optimization/quantization in advance and it requires the model exported to ONNX format. 

We notice that mlserver doesn't support ONNX model during loading (https://github.com/SeldonIO/MLServer/blob/master/runtimes/huggingface/mlserver_huggingface/common.py#L109). **So I wonder do we have a plan to support selection on ONNX/huggingface(pytorch_model.bin?) format?**

**Comment by adriangonz** [comment]
Hey @bugzyz ,

That's a great point.

It shouldn't be hard to add an extra parameter to control whether to load from `transformers` or not.

**Comment by bugzyz** [comment]
@adriangonz Thanks! That's what I'm asking. Looking forward to the update. :)
