### ISSUE TITLE
Add support for cuda drivers out of the box with mlserver build

### ISSUE THREAD

**Issue by pthalasta** [SeldonIO/MLServer#867]
Images built with mlserver do not have GPU drivers installed out of the box which results in errors when models require gpu for inferencing and need to use docker files to install the required driver. It would be great if mlserver image built comes with gpu drivers or provide an option to set the flag to true for gpu driver installation during build

**Comment by adriangonz** [comment]
Hey @pthalasta ,

Following up from our Slack thread, when using the HuggingFace runtime and / or GPU in (at least, some) custom models, those seem to be able to access the GPU successfully. Could you share what model framework you're using?

Nothing wrong with adding the GPU driver to the base image, but want to first validate whether it's 100% required and what side effects that could have.

**Comment by adriangonz** [comment]
Hey @pthalasta ,

Following up on this one, from my prev message, HuggingFace models seem to be able to use the GPU with the current base image. 

I'll close this one for now, but please do reopen it if you get a chance to provide more details or a minimal reproducible example.
