### ISSUE TITLE
[Feature request] optimum upgrade and enable GPU device selection for optimum in huggingface MLServer

### ISSUE THREAD

**Issue by bugzyz** [SeldonIO/MLServer#870]
Hi there,

We're recently working on the **ONNX model with GPU** in huggingface MLServer. We want to raise below 3 request for huggingface MLServer:

1. Enable onnx model loading as I mentioned in this issue (https://github.com/SeldonIO/MLServer/issues/852)
2. We also want to enable GPU inferencing on ONNX model too. I checked the issue mentioned in the  [comments](https://github.com/SeldonIO/MLServer/blob/master/runtimes/huggingface/mlserver_huggingface/common.py#L112-L114) and it seems they already provided fix for the issue. Could we resume to enable the GPU device for ONNX model?
3. We also noticed that current optimum version is low. As optimum released [1.5.0](https://github.com/huggingface/optimum/releases/tag/v1.5.0) which contains the [IO binding enhancement](https://github.com/huggingface/optimum/pull/421) that fix the low performance issue on GPU for ONNX model. We are requesting its upgrade to leverage this enhancement to avoid huge performance slowdown on optimum compared to transformers based on our [test](https://github.com/huggingface/optimum/issues/365).

Thanks! Looking forward to your reply:)

**Comment by adriangonz** [comment]
Hey @bugzyz,

Massive thanks for taking the time to try ONNX models in the Huggingface runtime :+1: 

This feedback is really useful. I think all three points make a lot of sense, so hopefully we can address them in the next version :+1:

**Comment by bugzyz** [comment]
@adriangonz Thank you for your supports! 😄

Btw, do you have the ETA for these features to be released or available on dev?

**Comment by adriangonz** [comment]
Hey @bugzyz ,

No ETA, but you can see the roadmap for the next `1.3.0` version in the link below:

https://github.com/SeldonIO/MLServer/projects/6?query=is%3Aopen+sort%3Aupdated-desc
