### ISSUE TITLE
Expected XGBoost model file "model.bst" extension is undocumented? 

### ISSUE THREAD

**Issue by rehevkor5** [SeldonIO/MLServer#892]
On https://github.com/SeldonIO/MLServer/blob/master/runtimes/xgboost/mlserver_xgboost/xgboost.py#L21 you can see that MLServer is looking for an XGBoost model file called "model.bst". However, I cannot find any reference to that file extension in the XGBoost documentation. As far as I can see, XGBoost's documented file extensions are:

- ".json" added in 1.0.0, an "open format that can be easily reused"
- ".ubj" for Universal Binary JSON format, available in 1.6.0
- ".model" for the "old binary internal format" prior to 1.0.0, as shown in examples

Where does MLServer get the ".bst" extension from, and what model format does it use? Shouldn't it use one of the extensions mentioned in the XGBoost documentation instead, to avoid ambiguity?

**Comment by adriangonz** [comment]
Hey @rehevkor5 ,

That's a great point. 

We mainly support the `*.bst` extension to keep compatibility with the older "non-v2 protocol" XGBoost servers in both Seldon Core and KServe. But TBH I don't know where the name comes from. Having said that, it seems that other solutions like [Vertex AI](https://cloud.google.com/vertex-ai/docs/training/exporting-model-artifacts) also refer to this `*.bst` extension, so it may be a remnant from the time when XGBoost didn't support the JSON format?

Keep in mind though, that MLServer also supports the `*.json` extension. By default, if you pass a folder as the model's URI, it will try to look for a `model.bst` or `model.json` files. Alternatively, you can specify any file name directly on the `parameters.uri` field of the `model-settings.json` file. 

Haven't read much about the `.ubj` or `.model` extensions. Would it be worth also supporting those on the  `mlserver-xgboost` runtime?

**Comment by rehevkor5** [comment]
> TBH I don't know where the name comes from.
> it may be a remnant from the time when XGBoost didn't support the JSON format?

Gotcha. I tried looking at the XGBoost code.

I'm not a C++ expert (it's been a while), but https://github.com/dmlc/xgboost/blob/v1.5.0/src/c_api/c_api.cc#L843 and https://github.com/dmlc/xgboost/blob/v1.5.0/src/c_api/c_api.cc#L862 only seems to check for "json". Otherwise, I assume it's calling `virtual void SaveModel(dmlc::Stream* fo) const = 0;` from learner.h, which must be implemented here https://github.com/dmlc/xgboost/blob/v1.5.0/src/learner.cc#L876 So, it looks like any extension other than "json" will use the old binary format.

> Haven't read much about the .ubj or .model extensions. Would it be worth also supporting those on the mlserver-xgboost runtime?

Regarding `.ubj`, I cannot see in the documentation how to tell which version of XGBoost each version of MLServer supports/includes. However, `.ubj` is only available starting in XGBoost 1.6.0. Is there some way to tell whether a specific MLServer version includes XGBoost 1.6.0? (Anything easier than, I suppose, opening an interactive shell into the Docker container & inspecting the libraries on disk?)

**Comment by rehevkor5** [comment]
But yes, I agree that MLServer should support `.ubj` if possible.
