### ISSUE TITLE
SeldonDeployment shows 'classifier' like model name instead custom name in manifest

### ISSUE THREAD

**Issue by noheroes** [SeldonIO/MLServer#921]
After deploy a custom SeldonDeployment manifest in kubernetes log appear that the name of model is classifier instead a custom name altovalor-m1.

apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: altovalor-m1
spec:
  annotations:
    seldon.io/istio-gateway: mesh
    seldon.io/istio-host: altovalor-m1
  name: altovalor-m1
  predictors:
    - annotations:
        seldon.io/svc-name: altovalor-m1
      componentSpecs:
      - spec:
          containers:
          - image: core.weird-logic.com/private-repository/mlserver-altovalor-m1-scoring:latest
            name: classifier
            securityContext:
              runAsUser: 1000
              readOnlyRootFilesystem: false
          imagePullSecrets:
          - name: regcredharbor
          terminationGracePeriodSeconds: 1
      graph:
        children: []
        endpoint:
          type: REST #GRPC
        name: classifier
        type: MODEL
      name: altovalor-m1
      replicas: 1

INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO:     Uvicorn running on http://0.0.0.0:6000 (Press CTRL+C to quit)
2022-12-28 23:46:25,666 [mlserver] INFO - Loaded model 'classifier' succesfully.

**Comment by noheroes** [comment]
Update: the issue occur when trying to use a base image with part of dockerfile generated by mlserver and another docker file with only the python code, i try again with the original and works fine. someone can explain me whats wrong with this approach? thanks.

**Comment by adriangonz** [comment]
Hey @noheroes ,

I think I'm missing some context here. From your last comment, do you mean that when using `mlserver build` it works as expected?

Generally, you want Seldon Core to override the model's name to ensure that it maps 1:1 with the step on your inference graph (which in this case is `classifier` - from the `spec.predictors[].graph.name` field in your `SeldonDeployment` manifest). Otherwise, the executor won't be able to find your model.

**Comment by noheroes** [comment]
I will explain better:
- Got a Dockerfile using mlserver dockerfile.
- From the dockerfile file I extracted the repetitive part, in order to use it to create a base image and achieve that the generation of the image with the remaining code of the Dockerfile is obtained more quickly.
- Trying to use the generated base image, when raising the container and loading the model, it shows that it has taken the name "classifier" instead of the name assigned for said model. Which does not happen if it is built using the original Dockerfile, where when the image is executed the model takes the correct name.
- Finally I could not get to use a base image and opted to use the Dockerfile obtained through mlserver cli.

**Comment by adriangonz** [comment]
Thanks for that update @noheroes . 

Just so I understand, when you say 

> it shows that it has taken the name "classifier" instead of the name assigned for said model

Could you clarify what is the "name assigned" and where does it come from?  Also, where does the "classifier" name come from?

**Comment by adriangonz** [comment]
Oh wait, just had a look at the sdep you linked above and noticed that the `classifier` name comes from there.

Seldon Core will inject that model name (i.e. `classifier`) into MLServer through an environment variable. From what you say, the stock Dockerfile doesn't pay attention to that variable, and instead overrides it with your custom one. Based on that, my guess is that your custom `Dockerfile` was missing the last lines from the stock one, where it reads your local's `model-settings.json` (i.e. the one embedded within your image) and injects that config instead:

https://github.com/SeldonIO/MLServer/blob/52c68a06d700d3f79a0ec0b511fac43e96d02f08/mlserver/cli/constants.py#L63-L64

Having said that, the behaviour in the latest version of MLServer around this has changed to allow the env var coming from Seldon Core to override whatever is present on the embedded `model-settings.json` file. This is generally the desired behaviour (see the reason in my prev comment).
