### ISSUE TITLE
Adding list of string type to the pydantic dataplane paramter field

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/MLServer#924]
I need to pass several types of metadata for each of my requests. @adriangonz as per our [community slack conversation](https://seldondev.slack.com/archives/C03DQFTFXMX/p1671494800794449) the `types.parameters()` is the correct way of adding such metadata. However, the available data types in parameters https://github.com/SeldonIO/MLServer/blob/c0d4ae9f3e2e75c12c038cbc8b63100f74dba5a4/mlserver/types/dataplane.py#L29 and https://github.com/SeldonIO/MLServer/blob/c0d4ae9f3e2e75c12c038cbc8b63100f74dba5a4/mlserver/types/dataplane.py#L30 are very limited. This could be enhanced by adding more data types to be sent over the API e.g. a list of strings was necessary for my use case and I had to do a workaround to send it as a string which was not ideal.

**Comment by saeid93** [comment]
Hey @adriangonz,
That makes sense, I agree that if it is part of the V2 protocol, then it should be coordinated with other stakeholders too. However, I think there should be some way to send metadata per request with formats other than strings. This has many potential use cases and I think worth discussing to be added in the V2 itself, is there a relevant repository forV2 protocol to open the same discussion there?

**Comment by adriangonz** [comment]
Not yet - but we're trying to coordinate other stakeholders to create a centralised place to discuss these type of requests.
