### ISSUE TITLE
`mlserver dockerfile` COPY failed

### ISSUE THREAD

**Issue by MuhammadAgf** [SeldonIO/MLServer#952]
I'm not sure if it's a bug or intended  (if it's intended I think we need to add Documentation on how to work with the `mlserver dockerfile` command)

I'd like to make a report that the Dockerfile can't be used as it is after executing `mlserver dockerfile .`

I got this error when executing `docker build -t mlserver-demo -f Dockerfile .`
```
Step 5/15 : COPY     ./environment.ym[l]     ./environment.yam[l]     ./conda.ym[l]     ./conda.yam[l]     .
COPY failed: no source files were specified
``` 

the fix that I made is by removing most of the `COPY` part on the Dockerfile (after the part below are deleted I can build the Docker image)

```
COPY \
     ./environment.ym[l] \
     ./environment.yam[l] \
     ./conda.ym[l] \
     ./conda.yam[l] \
     .
COPY \
     --chown=1000 \
     --from=env-builder \
     /envs/base.tar.g[z] \
     ./envs/base.tar.gz
COPY \
     ./settings.jso[n] \
     ./model-settings.jso[n] \
     ./requirements.tx[t] \
     .
```
here my directory structure:
```
.
├── Dockerfile
├── Makefile
├── models
│   └── text-clf.joblib
├── model-settings.json
└── requirements.txt
```

it's a simple sklearn pipeline model in the models directory
```json
{
    "name": "text-clf",
    "implementation": "mlserver_sklearn.SKLearnModel",
    "parameters": {
        "uri": "./models/text-clf.joblib",
        "version": "v0.1.0"
    }
}
```

**Comment by adriangonz** [comment]
Hey @MuhammadAgf ,

The `Dockerfile` used by MLServer requires [buildkit](https://docs.docker.com/build/buildkit/) to be enabled (i.e. the new Docker backend). There're several ways to enable it, one of them is by setting the `DOCKER_BUILDKIT=1` env var before calling `docker build`, e.g.

```
DOCKER_BUILDKIT=1 docker build ....
```

We'll keep this one open to add a note to the docs about buildkit.
