### ISSUE TITLE
Adding the per request trace latency information

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/MLServer#962]
Adding per-request latency information will be very useful for debugging, I do many workarounds to get these kinds of data right now but an adaptation of Triton Server per request Tracing https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md would be a very useful addition.

**Comment by adriangonz** [comment]
Hey @saeid93 ,

Totally agree - tracing would be a great addition.

That one is already on our sights, and tracked in #39, so I'll go ahead and close this one - happy to continue the discussion on the other issue though!
